FROM rust:1.82.0-slim-bookworm
RUN apt-get update
RUN apt-get upgrade
RUN apt-get install -y pkg-config
RUN apt-get install -y libssl-dev
RUN rustup target add wasm32-unknown-unknown
RUN cargo install --locked trunk

WORKDIR /usr/src/app
COPY . .

ENTRYPOINT ["trunk", "serve", "--config", "./trunk.toml"]
